
import { RawMaterial, Product, Order, OrderStatus, Staff, Expense, TranslationDictionary, Customer } from './types';

export const TRANSLATIONS: TranslationDictionary = {
  dashboard: { ar: 'لوحة القيادة', fr: 'Tableau de bord' },
  inventory: { ar: 'المخزون', fr: 'Inventaire' },
  production: { ar: 'الإنتاج والاستهلاك', fr: 'Production et Consommation' },
  orders: { ar: 'المبيعات والطلبات', fr: 'Ventes et Commandes' },
  staff: { ar: 'الموظفين', fr: 'Personnel' },
  customers: { ar: 'الزباين', fr: 'Clients' },
  finance: { ar: 'الصرف والدخل', fr: 'Revenus et Dépenses' },
  settings: { ar: 'الإعدادات', fr: 'Paramètres' },
  totalProduction: { ar: 'إجمالي الإنتاج', fr: 'Production Totale' },
  totalSales: { ar: 'إجمالي المبيعات', fr: 'Ventes Totales' },
  lowStock: { ar: 'تنبيهات المخزون', fr: 'Alerte Stock' },
  rawMaterials: { ar: 'المواد الخام', fr: 'Matières Premières' },
  finishedGoods: { ar: 'المنتجات', fr: 'Produits' },
  add: { ar: 'إضافة', fr: 'Ajouter' },
  edit: { ar: 'تعديل', fr: 'Modifier' },
  delete: { ar: 'حذف', fr: 'Supprimer' },
  name: { ar: 'الاسم', fr: 'Nom' },
  quantity: { ar: 'الكمية', fr: 'Quantité' },
  maxQuantity: { ar: 'السعة القصوى', fr: 'Capacité Max' },
  unit: { ar: 'الوحدة', fr: 'Unité' },
  status: { ar: 'الحالة', fr: 'Statut' },
  date: { ar: 'التاريخ', fr: 'Date' },
  actions: { ar: 'إجراءات', fr: 'Actions' },
  welcome: { ar: 'مرحباً بك في نظام المصنع', fr: 'Bienvenue au Système d\'Usine' },
  search: { ar: 'بحث...', fr: 'Rechercher...' },
  save: { ar: 'حفظ', fr: 'Enregistrer' },
  cancel: { ar: 'إلغاء', fr: 'Annuler' },
  customer: { ar: 'العميل', fr: 'Client' },
  amount: { ar: 'المبلغ', fr: 'Montant' },
  role: { ar: 'الوظيفة', fr: 'Rôle' },
  salary: { ar: 'الراتب', fr: 'Salaire' },
  category: { ar: 'التصنيف', fr: 'Catégorie' },
  utility: { ar: 'فواتير (ماء/كهرباء)', fr: 'Utilitaires' },
  maintenance: { ar: 'صيانة', fr: 'Maintenance' },
  other: { ar: 'أخرى', fr: 'Autre' },
  logout: { ar: 'تسجيل الخروج', fr: 'Déconnexion' },
  login: { ar: 'تسجيل الدخول', fr: 'Connexion' },
  password: { ar: 'كلمة المرور', fr: 'Mot de passe' },
  username: { ar: 'اسم المستخدم', fr: 'Nom d\'utilisateur' },
  all: { ar: 'الكل', fr: 'Tout' },
  paySalary: { ar: 'صرف الراتب', fr: 'Payer Salaire' },
  phone: { ar: 'رقم الهاتف', fr: 'Téléphone' },
  address: { ar: 'العنوان', fr: 'Adresse' },
  email: { ar: 'البريد الإلكتروني', fr: 'Email' },
  newCustomer: { ar: 'زبون جديد', fr: 'Nouveau Client' },
  selectCustomer: { ar: 'اختر الزبون', fr: 'Sélectionner le client' },
  dailyProduction: { ar: 'تسجيل الإنتاج', fr: 'Enregistrer Production' },
  dailyConsumption: { ar: 'تسجيل الاستهلاك', fr: 'Enregistrer Consommation' },
  recordProduction: { ar: 'إضافة منتج جاهز', fr: 'Ajouter Produit Fini' },
  selectProduct: { ar: 'اختر المنتج', fr: 'Sélectionner Produit' },
  invoice: { ar: 'فاتورة', fr: 'Facture' },
  printInvoice: { ar: 'طباعة الفاتورة', fr: 'Imprimer Facture' },
  advance: { ar: 'سلفة', fr: 'Avance' },
  requestAdvance: { ar: 'طلب سلفة', fr: 'Demander Avance' },
  income: { ar: 'الدخل', fr: 'Revenu' },
  expenses: { ar: 'المصروفات', fr: 'Dépenses' },
  netProfit: { ar: 'صافي الربح (المتبقي)', fr: 'Profit Net (Reste)' },
  addExpense: { ar: 'إضافة مصروف', fr: 'Ajouter Dépense' },
  description: { ar: 'الوصف', fr: 'Description' },
  price: { ar: 'السعر', fr: 'Prix' },
  item: { ar: 'الصنف', fr: 'Article' },
  total: { ar: 'الإجمالي', fr: 'Total' },
  success: { ar: 'تمت العملية بنجاح', fr: 'Opération réussie' },
  error: { ar: 'حدث خطأ', fr: 'Erreur survenue' },
  insufficientStock: { ar: 'عفواً، الكمية في المخزون لا تكفي', fr: 'Désolé, stock insuffisant' },
  insufficientRaw: { ar: 'تنبيه: المواد الخام غير كافية للإنتاج!', fr: 'Alerte: Matières premières insuffisantes!' },
  specifyOther: { ar: 'حدد نوع المصروف', fr: 'Précisez l\'autre dépense' },
  calendarEvents: { ar: 'الأحداث القادمة', fr: 'Événements à venir' },
  salaryDate: { ar: 'موعد الرواتب', fr: 'Date de salaire' },
  usedMaterial: { ar: 'المادة الخام المستهلكة', fr: 'Matière première consommée' },
  materialConsumed: { ar: 'الكمية المستهلكة', fr: 'Quantité consommée' },
  available: { ar: 'متوفر', fr: 'Disponible' },
  good: { ar: 'جيد', fr: 'Bon' },
  low: { ar: 'منخفض', fr: 'Faible' },
  critical: { ar: 'حرج (نفذ)', fr: 'Critique' },
  currentStock: { ar: 'المخزون الحالي', fr: 'Stock Actuel' },
  selectMaterial: { ar: 'اختر المادة الخام', fr: 'Sélectionner Matière' },
  status_PENDING: { ar: 'قيد الانتظار', fr: 'En attente' },
  status_PROCESSING: { ar: 'قيد التنفيذ', fr: 'En cours' },
  status_COMPLETED: { ar: 'مكتمل', fr: 'Terminé' },
  status_CANCELLED: { ar: 'ملغي', fr: 'Annulé' },
  unknown: { ar: 'غير معروف', fr: 'Inconnu' },
  dailyPerformance: { ar: 'الأداء المالي (آخر 7 أيام)', fr: 'Performance quotidienne (7 derniers jours)' },
  monthlyOverview: { ar: 'ملخص شهري', fr: 'Aperçu mensuel' },
  selectUser: { ar: 'اختر الموظف (المستخدم)', fr: 'Sélectionner l\'utilisateur' },
  newUser: { ar: 'مستخدم جديد +', fr: 'Nouvel utilisateur +' },
  purchaseMaterial: { ar: 'شراء / تجديد مواد خام', fr: 'Achat / Réapprovisionnement' },
  addedQuantity: { ar: 'الكمية الجديدة المضافة', fr: 'Quantité ajoutée' },
  totalCost: { ar: 'التكلفة الإجمالية', fr: 'Coût total' },
};

export const MOCK_RAW_MATERIALS: RawMaterial[] = [
  { id: '1', nameAr: 'ورق كرتون معاد تدويره', nameFr: 'Papier recyclé', quantity: 4500, maxQuantity: 5000, unit: 'kg', minLevel: 1000, supplier: 'Saudi Paper Co.', price: 2.5 },
  { id: '2', nameAr: 'نشاء', nameFr: 'Amidon', quantity: 120, maxQuantity: 200, unit: 'kg', minLevel: 50, supplier: 'ChemLink', price: 15 },
  { id: '3', nameAr: 'مواد تغليف بلاستيك', nameFr: 'Emballage Plastique', quantity: 10, maxQuantity: 50, unit: 'roll', minLevel: 20, supplier: 'PlastPack', price: 120 },
  { id: '4', nameAr: 'ماء صناعي', nameFr: 'Eau industrielle', quantity: 2000, maxQuantity: 10000, unit: 'l', minLevel: 2000, supplier: 'National Water', price: 0.1 },
  { id: '5', nameAr: 'أحبار طباعة', nameFr: 'Encres d\'imprimerie', quantity: 14, maxQuantity: 15, unit: 'kg', minLevel: 10, supplier: 'Colors Inc.', price: 250 },
];

export const MOCK_PRODUCTS: Product[] = [
  { id: '1', nameAr: 'طبق بيض (30 بيضة)', nameFr: 'Plateau Œufs (30)', quantity: 15000, maxQuantity: 20000, unit: 'plate', price: 0.5 },
  { id: '2', nameAr: 'كرتون بيض (12 بيضة)', nameFr: 'Carton Œufs (12)', quantity: 4500, maxQuantity: 10000, unit: 'carton', price: 0.75 },
  { id: '3', nameAr: 'طبق بيض (15 بيضة)', nameFr: 'Plateau Œufs (15)', quantity: 2000, maxQuantity: 5000, unit: 'plate', price: 0.4 },
  { id: '4', nameAr: 'طبق بيض ملون (30)', nameFr: 'Plateau Coloré (30)', quantity: 500, maxQuantity: 1000, unit: 'plate', price: 0.6 },
];

export const MOCK_CUSTOMERS: Customer[] = [
  { id: '1', name: 'مزارع القصيم', phone: '0505123456', email: 'info@qassimfarms.com', address: 'Buraidah, Industrial City' },
  { id: '2', name: 'سوبر ماركت التميمي', phone: '0112345678', email: 'procurement@tamimimarkets.com', address: 'Riyadh, Exit 5' },
  { id: '3', name: 'مخابز الأرياف', phone: '0555987654', email: 'orders@aryafbakery.com', address: 'Jeddah, Rawdah Dist' },
  { id: '4', name: 'دواجن الوطنية', phone: '0165551111', email: 'sales@watania.com.sa', address: 'Qassim, Highway 1' },
];

export const MOCK_ORDERS: Order[] = [
  { id: '101', customerId: '1', customerName: 'مزارع القصيم', date: '2023-10-25', status: OrderStatus.COMPLETED, totalAmount: 5000, items: [{productId: '1', productName: 'طبق بيض (30)', quantity: 10000, unitPrice: 0.5, total: 5000}] },
  { id: '102', customerId: '2', customerName: 'سوبر ماركت التميمي', date: '2023-10-26', status: OrderStatus.PROCESSING, totalAmount: 1200, items: [] },
  { id: '103', customerId: '3', customerName: 'مخابز الأرياف', date: '2023-10-27', status: OrderStatus.PENDING, totalAmount: 850, items: [] },
];

export const MOCK_STAFF: Staff[] = [
  { id: '1', name: 'Mohammed Ali', roleAr: 'مدير المصنع', roleFr: 'Directeur d\'usine', salary: 15000, lastPaymentDate: '2023-09-30', advanceTaken: 0, password: 'admin' },
  { id: '2', name: 'Youssef Ahmed', roleAr: 'فني تشغيل', roleFr: 'Opérateur', salary: 5000, lastPaymentDate: '2023-10-30', advanceTaken: 500, password: '1234' },
  { id: '3', name: 'Sarah Salem', roleAr: 'محاسب', roleFr: 'Comptable', salary: 7000, lastPaymentDate: '2023-09-30', advanceTaken: 0, password: '1234' },
  { id: '4', name: 'Khalid Omar', roleAr: 'سائق فورك ليفت', roleFr: 'Chariot élévateur', salary: 4500, lastPaymentDate: '2023-10-01', advanceTaken: 0, password: '1234' },
  { id: '5', name: 'Ibrahim Hassan', roleAr: 'عامل خط إنتاج', roleFr: 'Ouvrier', salary: 3500, lastPaymentDate: '2023-10-01', advanceTaken: 200, password: '1234' },
];

export const MOCK_EXPENSES: Expense[] = [
  { id: '1', type: 'expense', category: 'Utility', description: 'Electric Bill - Oct', amount: 4500, date: '2023-10-01' },
  { id: '2', type: 'expense', category: 'Maintenance', description: 'Conveyor Belt Repair', amount: 1200, date: '2023-10-15' },
  { id: '3', type: 'expense', category: 'RawMaterial', description: 'Water Tank Refill', amount: 300, date: '2023-10-20' },
  { id: '4', type: 'income', category: 'Sales', description: 'Order #101 - Completed', amount: 5000, date: '2023-10-25' },
  { id: '5', type: 'expense', category: 'Salary', description: 'Worker Salaries', amount: 8000, date: '2023-10-30' },
];